{
  "code":500,
  "message":"Bad Request",
  "description":"The server encountered error, please to try to reach support team",
  "datetime":"2022-01-08T09:19:00Z",
  "transactionID":"3a1c05f2-6e7d-4455-9b12-bb1adfb57d72"
}